version: "3.9"

services:
  node-finder:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 6
    volumes:
      - ./config.toml:/config.toml

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blockchains
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

